/**
 * @file example_status.cpp
 * @brief Example Draconis++ info provider plugin.
 */

#include <format>

#include <Drac++/Core/Plugin.hpp>

#include <Drac++/Utils/Types.hpp>

#if DRAC_PRECOMPILED_CONFIG
  // In precompiled builds, this file is generated by flake.nix into this
  // plugin directory. Keep plugin-specific config local to the plugin.
  #include "config.hpp"
#endif

using namespace draconis::core::plugin;
using namespace draconis::utils::types;

namespace {
  // Keep collected data in a small struct. Bigger plugins usually fill this
  // from collectData(), cache it, and serialize it in toJson()/getFields().
  struct ExampleStatusData {
    String message;
  };

  class ExampleStatusPlugin final : public IInfoProviderPlugin {
   public:
    ExampleStatusPlugin() {
      m_metadata = {
        .name         = "Example Status",
        .version      = "0.1.0",
        .author       = "Your Name",
        .description  = "Provides a configurable example status message",
        .type         = PluginType::InfoProvider,
        // Set runtime capability flags honestly. Available flags are:
        // requiresNetwork, requiresFilesystem, requiresAdmin, requiresCaching.
        .dependencies = {},
      };
    }

    [[nodiscard]] auto getMetadata() const -> const PluginMetadata& override {
      return m_metadata;
    }

    auto initialize(const PluginContext& ctx, PluginCache& cache) -> Result<Unit> override {
      (void)ctx;
      (void)cache;

#if DRAC_PRECOMPILED_CONFIG
      // The generated config.hpp defines this constant. This path avoids TOML
      // entirely when Draconis++ is built in precompiled config mode.
      m_data.message = draconis::config::EXAMPLE_STATUS_MESSAGE;
#else
      // Runtime builds can read ctx.configDir / "example_status.toml" here.
      // This template keeps the runtime path simple so the plugin stays tiny.
      m_data.message = "Hello from an external Draconis++ plugin";
#endif

      m_ready = true;
      return {};
    }

    auto shutdown() -> Unit override {
      m_ready = false;
    }

    [[nodiscard]] auto isReady() const -> bool override {
      return m_ready;
    }

    [[nodiscard]] auto isEnabled() const -> bool override {
      return true;
    }

    [[nodiscard]] auto getProviderId() const -> String override {
      // This provider ID becomes the plugin key in output and UI lookups, e.g.
      // "plugin.example_status" in layouts.
      return "example_status";
    }

    auto collectData(PluginCache& cache) -> Result<Unit> override {
      (void)cache;
      // Gather fresh data here. Use cache.get<T>() / cache.set<T>() for
      // expensive work such as network calls, subprocesses, or filesystem scans.
      return {};
    }

    [[nodiscard]] auto toJson() const -> Result<String> override {
      return std::format(R"({{"message":"{}"}})", m_data.message);
    }

    [[nodiscard]] auto getFields() const -> Map<String, String> override {
      // Fields are flattened by Draconis++ for compact/template output.
      return {
        { "message", m_data.message },
      };
    }

    [[nodiscard]] auto getDisplayValue() const -> Result<String> override {
      return m_data.message;
    }

    [[nodiscard]] auto getDisplayIcon() const -> String override {
      return "  ";
    }

    [[nodiscard]] auto getDisplayLabel() const -> String override {
      return "Example";
    }

    [[nodiscard]] auto getLastError() const -> Option<String> override {
      return None;
    }

   private:
    PluginMetadata    m_metadata;
    ExampleStatusData m_data;
    bool              m_ready = false;
  };
} // namespace

// This macro exports the dynamic plugin entry points, or the static
// registration hook when the plugin is compiled into Draconis++.
DRAC_PLUGIN(ExampleStatusPlugin)
